### ISSUE TITLE
goal: downloadable binary builds?

### ISSUE THREAD

**Issue by adrelanos** [Whonix/Gentoo-Port#3]
Is the goal of the project to provide binary downloadable images?

Providing code to build hardened Gentoo bases Whonix images is one thing. Providing redistributable binary images another one.

**Comment by martinholovsky** [comment]
Hi Patrick,

Gentoo is compiled based on HW which you have. For example Securix is using in GCC option -march=native (http://wiki.gentoo.org/wiki/GCC_optimization) so it will enable all instruction sets (flags) which your CPU can handle.

Above of that Securix is not supporting 32bit systems, due to negative performance impact of some security features on 32bit systems. Even 10 years old computers/server are 64bit capable, so I don't see a good reason to have backward compatibility.

I was thinking about VirtualBox/VMware image only.

Is that sufficient?

Thank you

**Comment by an0ncs0** [comment]
agreed for the 64bit part.
Binaries are much harder to audit. therefore we compile from sources only on intended platforms.
not everything will compile with the harden flags (and grsec). That makes things much more fun! :) 
We will, in time, have a rep of sources known to compile with all security features (first step).
We could maybe perhaps eventually make other reps with different level of security for sources known not to compile with all security options: that can lead to well configures HIDS/IDS IPS & honeypots/honeynets. (but first things first..)
If a source doesn't compile, we blacklist it. pure & simple.
Computation power can be made available upon request for cross compilation (details to be discussed privately)

**Comment by adrelanos** [comment]
According to Sponsor B, [downloadable](https://www.whonix.org/wiki/Download) file downloads are not a goal. Not providing, maintaining them safes lots of effort.

**Comment by adrelanos** [comment]
Noted here:
https://www.whonix.org/wiki/Dev/Gentoo
